---
exclude_paths:
  - "tck/**"

engines:
  bandit:
    enabled: true
    arguments:
      - "-s"
      - "B101"
    exclude_paths:
      - tests/**
  pylint:
    enabled: true
    rules:
      assert_used:
        skips:
          - "*_test.py"
          - "*test_*.py"
