---
exclude_paths:
  - "tck/**"

engines:
  bandit:
    enabled: true
    arguments:
      - "-s"
      - "B101"
    exclude_paths:
      - tests/**
  pylintpython3:
    enabled: true
    exclude_paths:
      - "**/*_test.py"
      - "**/test_*.py"
